services:
  nginx:
    image: nginx
    ports:
      - "81:80" # whatever is hit on 81 local will be send to 80 on docker
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './static_files:/usr/share/nginx/html/static_files'
